### ISSUE TITLE
Lidar converter

### ISSUE THREAD

**Issue by ffent** [tudelft-iv/multi_sensor_calibration#21]
Hi, 

I really want to thank you for your great work. I'm currently working on a lidar converter to use your code with a lidar sensor different from a Velodyne sensor and would like to ask for some further information. Could you please provide the PointField message as part of the PointCloud2 message of the /velodyne_points ROS topic, which the lidar_detector is subscribing to?

I'm currently working with the following PointField message, but getting errors from the lidar detection node.
<details>
<summary>sensor_msgs/PointField</summary>
<br>

```
fields:
    -
        name: "x"
        offset: 0
        datatype: 7
        count: 1
    -
        name: "y"
        offset: 4
        datatype: 7
        count: 1
    -
        name: "z"
        offset: 8
        datatype: 7
        count: 1
    -
        name: "intensity"
        offset: 12
        datatype: 7
        count: 1
    -
        name: "ring"
        offset: 16
        datatype: 4
        count: 1
```

</details>
<br />
